apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: observability
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/k8s-observability
      sourceRef:
        kind: GitRepository
        name: oke-day2
      interval: 1m